using System.Text.RegularExpressions;

namespace Johannes
{
	public class TypstExporter : AbstractExporter
	{
		private readonly FileStream _handle;
		private readonly string _supportFunctionsFilename;
		private const string AutoGeneratedFunctionComment = """
			/*
			 * Fonction insérée automatiquement.
			 * Les modifications seront conservées.
			 */
			""";

		private static readonly SupportFunction[] DefaultSupportFunctions =
		[
			new(
				"ellipsis",
				"""
				#let ellipsis() = {
				  align(center, text("***"))
				}
				""")
		];

		public TypstExporter(string baseFile)
		{
			var filename = $"{baseFile}.typ";
			_supportFunctionsFilename = Path.Combine(
				Path.GetDirectoryName(filename) ?? Directory.GetCurrentDirectory(),
				"support-functions.typ");

			EnsureSupportFunctions(_supportFunctionsFilename, DefaultSupportFunctions);

			// delete file if it already exists to avoid appending to an old file
			if (File.Exists(filename))
			{
				File.Delete(filename);
			}
			_handle = File.OpenWrite(filename);
			Write("#import \"/support-functions.typ\" : *\n\n");
		}

		private static void EnsureSupportFunctions(string filename, IEnumerable<SupportFunction> requiredFunctions)
		{
			if (!File.Exists(filename))
			{
				File.WriteAllText(filename, string.Empty);
			}

			var content = File.ReadAllText(filename);
			var uncommentedContent = RemoveCommentsAndStrings(content);
			var missingFunctions = requiredFunctions
				.Where(function => !HasFunction(uncommentedContent, function.Name))
				.ToList();

			if (missingFunctions.Count == 0)
			{
				return;
			}

			using var writer = File.AppendText(filename);
			if (content.Length > 0 && !content.EndsWith('\n'))
			{
				writer.WriteLine();
			}

			foreach (var function in missingFunctions)
			{
				writer.WriteLine(AutoGeneratedFunctionComment);
				writer.WriteLine(function.Definition);
			}
		}

		private static bool HasFunction(string content, string functionName) =>
			Regex.IsMatch(content, $@"#let\s+{Regex.Escape(functionName)}\s*\(");

		private static string RemoveCommentsAndStrings(string content)
		{
			var result = new System.Text.StringBuilder(content.Length);
			var inLineComment = false;
			var blockCommentDepth = 0;
			var inString = false;
			var isEscaped = false;

			for (var index = 0; index < content.Length; index++)
			{
				var current = content[index];
				var next = index + 1 < content.Length ? content[index + 1] : '\0';

				if (inLineComment)
				{
					if (current is '\r' or '\n')
					{
						inLineComment = false;
						result.Append(current);
					}
					else
					{
						result.Append(' ');
					}

					continue;
				}

				if (blockCommentDepth > 0)
				{
					if (current == '/' && next == '*')
					{
						blockCommentDepth++;
						result.Append("  ");
						index++;
					}
					else if (current == '*' && next == '/')
					{
						blockCommentDepth--;
						result.Append("  ");
						index++;
					}
					else
					{
						result.Append(current is '\r' or '\n' ? current : ' ');
					}

					continue;
				}

				if (inString)
				{
					if (current is '\r' or '\n')
					{
						inString = false;
						result.Append(current);
					}
					else
					{
						result.Append(' ');
						if (current == '"' && !isEscaped)
						{
							inString = false;
						}

						isEscaped = current == '\\' && !isEscaped;
					}

					continue;
				}

				if (current == '/' && next == '/')
				{
					inLineComment = true;
					result.Append("  ");
					index++;
				}
				else if (current == '/' && next == '*')
				{
					blockCommentDepth = 1;
					result.Append("  ");
					index++;
				}
				else if (current == '"')
				{
					inString = true;
					isEscaped = false;
					result.Append(' ');
				}
				else
				{
					result.Append(current);
				}
			}

			return result.ToString();
		}

		protected void Write(string data) => _handle.Write(System.Text.Encoding.UTF8.GetBytes(data));

		public override void Paragraph(string styleId, List<ParagraphRun> runs)
		{
			var content = UnRun(runs);

			switch (styleId)
			{
				case "Titre1":
					Write($"= {content}\n\n");
					break;
				case "Normal":
					Write($"{content}\n\n");
					break;
				case "Ellipse":
				case "Elipse":
					Write("#ellipsis()\n\n");
					break;
				case "Titre":
					Write($"#titre()[\n{content}\n]\n\n");
					break;
				default:
					var styleFunction = SupportFunction.ForStyle(styleId);
					EnsureSupportFunctions(_supportFunctionsFilename, [styleFunction]);
					Write($"#{styleFunction.Name}([\n{content}\n])\n\n");
					break;
			}
		}

		internal static string UnRun(List<ParagraphRun> runs)
		{
			var sb = new System.Text.StringBuilder();
			foreach (var run in runs)
			{
				var content = "";

				foreach (var c in run.content)
				{
					var bytes = System.Text.Encoding.UTF8.GetBytes([c]);
					content += Replace(c, bytes);
				}

				if (run.isItalic)
				{
					content = $"_{content}_";
				}
				sb.Append(content);
			}

			var data = sb.ToString();
			data = SpaceBeforeQuestionMarkRegex().Replace(data, "~?");
			data = SpaceAfterQuestionMarkRegex().Replace(data, "?~");
			data = SpaceBeforeExclamationMarkRegex().Replace(data, "~!");
			data = SpaceAfterExclamationMarkRegex().Replace(data, "!~");
			data = ColonRegex().Replace(data, "~:");
			data = SemiColonRegex().Replace(data, "~;");

			return data;
		}

		public static string Replace(char c, byte[] bytes) => bytes switch
		{
			// em dash
			[0xE2, 0x80, 0x94] => "---",
			// non-breaking space
			[0xC2, 0xA0] => "~",
			_ => $"{c}",
		};

		public override void FinishExport()
		{
			_handle.Flush();
			_handle.Close();
		}

		private sealed record SupportFunction(string Name, string Definition)
		{
			public static SupportFunction ForStyle(string styleId)
			{
				var name = $"style_{styleId}";
				return new(
					name,
					$$"""
					#let {{name}}(body) = {
					  [#body]
					}
					""");
			}
		}
	}
}
